version: '3.5'

networks:
  mynet1:
    external: true
    name: mynet1

services:
  ubuntux:
    build:
      context: .
      dockerfile: Dockerfile
    image: ntw/ubuntux
    container_name: ubuntux-1
    hostname: ubuntux-1
    dns: 8.8.8.8
    user: "0"
    ports:
      - "5901:5901"
      - "6901:6901"
    networks:
      - mynet1
    volumes:
      - ./data/shared:/usr/data/shared
